### ISSUE TITLE
创建者的id建议也一起给出来

### ISSUE THREAD

**Issue by SekaiArendelle** [tiao2/Physics-Lab-Organize#1]

**Comment by tiao2** [comment]
我也准备搞这个
`创建者:`*`username`*`,`*`userID`*<br/>
或
`创建者昵称: `*`username`*`,`<br/>
`创建者序列号: `*`userID`*
<br/>
哪个更合适？

**Comment by SekaiArendelle** [comment]
第一个吧
我的想法是：昵称 (序列号)

**Comment by tiao2** [comment]
做好了
